name: protoc-multi-language-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Build
      run: docker build -t docker.pkg.github.com/caramis/protoc-multi-language-actions/protoc:latest .
    - name: Publish
      run: |
        docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker push docker.pkg.github.com/caramis/protoc-multi-language-actions/protoc:latest
